# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc9d4be7b051f2b5d152241a5addc70a118d6c2addd64d38c9bfc7b8e3015930345563aa5d165d76ee519c9e5b306ab6b43bd06ececa4471b9cb0d3a48ba85c4

test:
  secret_key_base: c818a481ef18f3d5e26fcc5226e0f22509b02ea076d13b169415e9f0a6ee77b3bfa6f200bbccc27808b9ee47da2e4e47448798b40470ff01acd6338c119d3096

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
